import os
Import('env', 'arch', 'common', 'cereal', 'messaging')

sensors_ka2 = [
  'sensors/i2c_sensor.cc',
  'sensors/icm42670_accel.cc',
  'sensors/icm42670_gyro.cc',
  'sensors/icm42670_temp.cc',
  'sensors/lis2mdl_magn.cc',
  'sensors/lis2mdl_temp.cc',
]

libs = [common, cereal, messaging, 'capnp', 'zmq', 'kj', 'pthread']
if arch == "larch64" or os.path.isfile('/KA2'):
  libs.append('i2c')

env.Program('sensord', ['sensors_ka2.cc'] + sensors_ka2, LIBS=libs)
